name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "37 */8 * * *" # Runs every 8 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Chrome & Chromedriver
        run: |
          choco install googlechrome chromedriver -y
          echo "Chrome and Chromedriver installed."

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Chrome and Chromedriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run unlock script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSSTDIO: utf-8
        run: python auto_login.py
